version: '3.8'

services:

  # PostgreSQL Database Service
  pessoa-db:
    image: postgres:17-alpine
    container_name: pessoa_db
    environment:
      POSTGRES_DB: pessoa_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/script.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pessoa_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '1GB'

  # Java Application Service 1
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "80"
    depends_on:
      pessoa-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pessoa-db:5432/pessoa_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Debug flags removidas pois quebram a imagem nativa
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '700M'

  # Java Application Service 2
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "80"
    depends_on:
      pessoa-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pessoa-db:5432/pessoa_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Debug flags removidas pois quebram a imagem nativa
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '700M'

  # Nginx Reverse Proxy Service
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '600M'

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge