version: '3.8'

services:

  # PostgreSQL Database Service
  pessoa-db:
    image: postgres:17-alpine
    container_name: pessoa_db
    environment:
      POSTGRES_DB: pessoa_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" # Expose DB port to the host for direct access with a DB client
    restart: always

  # Java Application Service
  app1:
    build:
      context: . # Path to the app's Dockerfile
      dockerfile: app/Dockerfile # Specify the Dockerfile if it's not named 'Dockerfile'
    restart: on-failure
    expose:
      - "80" # Expose for internal communication within the Docker network
    ports:
      - "5005:5005"
    depends_on:
      - pessoa-db # Wait for the database to be ready
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pessoa-db:5432/pessoa_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      _JAVA_OPTIONS: >
        -Xdebug 
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    deploy:
      resources:
        limits:
          cpus: '1' # Limita o serviço a usar no máximo 50% de um núcleo de CPU
          memory: '1.5GB' # Limita o serviço a usar no máximo 512 Megabytes de RAM

  app2:
    build:
      context: . # Path to the app's Dockerfile
      dockerfile: app/Dockerfile # Specify the Dockerfile if it's not named 'Dockerfile'
    restart: on-failure
    expose:
      - "80" # Expose for internal communication within the Docker network
    ports:
      - "5006:5006"
    depends_on:
      - pessoa-db # Wait for the database to be ready
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pessoa-db:5432/pessoa_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      _JAVA_OPTIONS: >
        -Xdebug 
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limita o serviço a usar no máximo 50% de um núcleo de CPU
          memory: '1.5GB' # Limita o serviço a usar no máximo 512 Megabytes de RAM

  # Nginx Reverse Proxy Service
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "9999:9999" # Main entry point for all traffic
    depends_on:
      - app1
      - app2

# Volumes to persist database data
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge

