server.port=80
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://pessoa-db:5432/pessoa_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=45
spring.datasource.hikari.minimum-idle=45
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000