worker_processes auto;

events {
    worker_connections 5000;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    upstream java_apps {
        least_conn;
        server app1:80;
        server app2:80;
        keepalive 500;
    }

    server {
        listen 9999;
        server_name localhost;

        location / {
            proxy_pass http://java_apps;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Mantivemos apenas o Host, necessário para o header 'Location' correto
            proxy_set_header Host $host;
        }
    }
}